accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("update/", views.update, name="update"),
    path("delete/", views.delete, name="delete"),
    path("password_change/", views.password_change, name="password_change"),
    path("follow/<int:user_pk>/", views.follow, name="follow"),
    path("mypage/", views.mypage, name="mypage"),
    path(
        "search_friends/<str:search_query>/",
        views.search_friends,
        name="search_friends",
    ),
    path("check_duplicate/", views.check_duplicate, name="check_duplicate"),
    path(
        "mark_as_read/<int:notification_pk>/", views.mark_as_read, name="mark_as_read"
    ),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path("main/", views.main, name="main"),
    path("create/<str:post_date>/", views.create, name="create"),
    path("check_post/<str:post_date>/", views.check_post, name="check_post"),
    path("detail/<int:user_pk>/<str:post_date>/", views.detail, name="detail"),
    path("update/<int:post_pk>/", views.update, name="update"),
    path("delete/<int:post_pk>/", views.delete, name="delete"),
    path("comment_create/<int:post_pk>/", views.comment_create, name="comment_create"),
    path(
        "comment_delete/<int:post_pk>/<int:comment_pk>/",
        views.comment_delete,
        name="comment_delete",
    ),
    path(
        "comment_update/<int:post_pk>/<int:comment_pk>/",
        views.comment_update,
        name="comment_update",
    ),
]

skyful/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("accounts/", include("accounts.urls")),
    path("posts/", include("posts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings


class User(AbstractUser):
    def image_path(instance, filename):
        return f"accounts/{instance.username}/{filename}"

    username = models.CharField(max_length=20, unique=True)
    nickname = models.CharField(max_length=20, unique=True)
    profile_img = ProcessedImageField(
        upload_to=image_path,
        processors=[ResizeToFill(200, 200)],
        options={"quality": 90},
        null=True,
        blank=True,
    )
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )


class Notification(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    UserChangeForm,
    PasswordChangeForm,
)
from django.contrib.auth import get_user_model


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label="아이디",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
            }
        ),
    )
    password = forms.CharField(
        label="비밀번호",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
            }
        ),
    )


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label="* 아이디",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
            }
        ),
    )
    nickname = forms.CharField(
        label="* 닉네임",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-control form-field",
            }
        ),
    )
    password1 = forms.CharField(
        label="* 비밀번호",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
            }
        ),
    )
    password2 = forms.CharField(
        label="* 비밀번호 확인",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
            }
        ),
    )
    profile_img = forms.ImageField(
        label="프로필 이미지(선택)", widget=forms.ClearableFileInput(), required=False
    )

    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "nickname",
            "password1",
            "password2",
            "profile_img",
        )


class CustomUserChangeForm(UserChangeForm):
    nickname = forms.CharField(
        label="* 닉네임",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
            }
        ),
    )
    profile_img = forms.ImageField(
        label="프로필 이미지(선택)", widget=forms.ClearableFileInput(), required=False
    )

    class Meta:
        model = get_user_model()
        fields = (
            "nickname",
            "profile_img",
        )


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="기존 비밀번호",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
            }
        ),
    )
    new_password1 = forms.CharField(
        label="새 비밀번호",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
            }
        ),
    )
    new_password2 = forms.CharField(
        label="새 비밀번호 확인",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
            }
        ),
    )

    class Meta(PasswordChangeForm):
        fields = "__all__"

accounts/views.py
from django.shortcuts import render, redirect
from posts.models import Post
from .models import Notification
from .forms import (
    CustomAuthenticationForm,
    CustomUserCreationForm,
    CustomUserChangeForm,
    CustomPasswordChangeForm,
)
from django.contrib.auth import (
    login as auth_login,
    logout as auth_logout,
    update_session_auth_hash,
    get_user_model,
    authenticate,
)
from django.contrib.auth.hashers import check_password
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.contrib import messages
from django.db.models import Q
import os


def login(request):
    if request.user.is_authenticated:
        return redirect("posts:main")

    if request.method == "POST":
        form = CustomAuthenticationForm(request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect("posts:main")
        else:
            messages.error(request, "아이디 또는 비밀번호가 올바르지 않습니다.")
    else:
        form = CustomAuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect("posts:main")


def signup(request):
    if request.user.is_authenticated:
        return redirect("posts:main")

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("posts:main")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("posts:main")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


@login_required
def delete(request):
    if request.user.profile_img:
        if os.path.isfile(request.user.profile_img.path):
            os.remove(request.user.profile_img.path)
    request.user.delete()
    auth_logout(request)
    return redirect("posts:main")


@login_required
def password_change(request):
    if request.method == "POST":
        form = CustomPasswordChangeForm(request.user, request.POST)
        old_password = request.POST.get("old_password")
        new_password = request.POST.get("new_password1")

        if check_password(old_password, request.user.password):
            if old_password == new_password:
                messages.error(
                    request,
                    "현재 비밀번호와 변경하려는 비밀번호가 동일합니다.",
                )
        else:
            messages.error(
                request,
                "현재 비밀번호가 일치하지 않습니다.",
            )
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            redirect("posts:main")
    else:
        form = CustomPasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/password_change.html", context)


@login_required
def follow(request, user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)

    if person != request.user:
        if request.user in person.followers.all():
            person.followers.remove(request.user)
        else:
            person.followers.add(request.user)
            Notification.objects.create(
                user=person,
                message=f"{request.user.nickname}님이 당신을 팔로우했습니다.",
            )
        return redirect("accounts:mypage")

    return redirect("posts:main")


@login_required
def mypage(request):
    User = get_user_model()
    person = User.objects.get(pk=request.user.pk)
    followings = person.followings.all()
    followers = person.followers.all()
    shared_posts_by_me = Post.objects.filter(
        user=person, shared_with__isnull=False
    ).order_by("-date")
    shared_posts_to_me = person.shared_posts.all().order_by("-date")
    posts_with_my_comments = (
        Post.objects.filter(comment__user=person)
        .exclude(user=person)
        .distinct()
        .order_by("-date")
    )
    posts_with_comments_by_others = (
        Post.objects.filter(comment__user__in=followings, user=person)
        .distinct()
        .order_by("-date")
    )

    context = {
        "person": person,
        "followings": followings,
        "followers": followers,
        "shared_posts_by_me": shared_posts_by_me,
        "shared_posts_to_me": shared_posts_to_me,
        "posts_with_my_comments": posts_with_my_comments,
        "posts_with_comments_by_others": posts_with_comments_by_others,
    }
    return render(request, "accounts/mypage.html", context)


@login_required
def search_friends(request, search_query):
    User = get_user_model()
    if request.method == "GET":
        results = User.objects.filter(
            Q(username__icontains=search_query) | Q(nickname__icontains=search_query)
        ).exclude(pk=request.user.pk)

        results_list = [
            {
                "pk": user.pk,
                "username": user.username,
                "nickname": user.nickname,
                "profile_img": user.profile_img.url if user.profile_img else None,
                "is_following": user.followers.filter(pk=request.user.pk).exists(),
            }
            for user in results
        ]

        return JsonResponse(results_list, safe=False)
    return JsonResponse([], safe=False)


@csrf_exempt
def check_duplicate(request):
    User = get_user_model()
    if request.method == "POST":
        username = request.POST.get("username")
        nickname = request.POST.get("nickname")

        username_exists = User.objects.filter(username=username).exists()
        nickname_exists = User.objects.filter(nickname=nickname).exists()

        result_data = {
            "username": {
                "exists": username_exists,
                "message": "사용 중인 아이디입니다.",
            },
            "nickname": {
                "exists": nickname_exists,
                "message": "사용 중인 닉네임입니다.",
            },
        }

        return JsonResponse(result_data)


@login_required
def mark_as_read(request, notification_pk):
    if request.method == "POST":
        notification = Notification.objects.get(pk=notification_pk)
        notification.is_read = True
        notification.save()
        context = {
            "success": True,
            "unread_count": request.user.notification_set.filter(is_read=False).count(),
        }
        return JsonResponse(context)

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static "css/login.css" %}">
{% endblock style %}

{% block content %}
  <div class="main-box">
    <div id="carousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static "img/clouds.jpg" %}" alt="맑은 하늘 이미지" />
        </div>
        <div class="carousel-item">
          <img src="{% static "img/sunset.jpg" %}" alt="노을빛 하늘 이미지" />
        </div>
        <div class="carousel-item">
          <img src="{% static "img/gloomy.jpg" %}" alt="흐린 하늘 이미지" />
        </div>
        <div class="carousel-item">
          <img src="{% static "img/moon.jpg" %}" alt="달이 뜬 밤하늘 이미지" />
        </div>
      </div>
      <div class="phrases">
        <p>당신의 오늘 하늘은 어땠나요?</p>
        <p>흐리거나 비가 왔대도 괜찮아요.</p>
        <p>모든 하늘은 아름다움을 담고 있어요,</p>
        <p>그리고 당신도 마찬가지에요.</p>
      </div>
    </div>
    
    <div class="login-form">
      <form action="{% url "accounts:login" %}" method="POST">
        {% csrf_token %}
        {% for inputs in form %}
        <label>{{ inputs.label }}
          <p>{{ inputs }}</p>
        </label>
        <br>
        {% endfor %}
        <button type="submit">로그인</button>
      </form>
    </div>
    <a href="{% url "accounts:signup" %}">회원가입</a>
  </div>
{% endblock content %}

{% block js %}
<script>
  {% if messages %}
    {% for message in messages %}
      alert("{{ message }}")
    {% endfor %}
  {% endif %}
</script>
{% endblock js %}

accounts/templates/accounts/mypage.html
{% extends "base.html" %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static "css/mypage.css" %}"> 
{% endblock style %}

{% block content %}
  <div class="main-box">
    <div class="profile-box">
      {% if person.profile_img %}
      <img src="{{ person.profile_img.url }}" alt="프로필 이미지" />
      {% else %} <img src="{% static "img/user.png" %}" alt=""> {% endif %}
      <p>{{ person.nickname }} ({{ person.username }})</p>
      <p class="follow-list">
        <button type="button" data-bs-toggle="modal" data-bs-target="#followings">
          팔로잉 {{ followings.count }}
        </button>
        |
        <button type="button" data-bs-toggle="modal" data-bs-target="#followers">
          팔로워 {{ followers.count }}
        </button>
      </p>

      <div class="modal fade" id="followings" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">팔로잉({{ followings.count }})</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              {% if followings.count > 0 %}
                {% for following in followings %}
                <div class="friend-box">
                  <div class="friend-info-box">
                    {% if following.profile_img %}
                      <img src="{{ following.profile_img.url }}" alt="프로필 이미지">
                    {% else %}
                      <img src="{% static "img/user.png" %}" alt="기본 프로필 이미지">
                    {% endif %}
                    <span>
                      {{ following.nickname }}({{ following.username }})
                    </span>
                  </div>
                  <form action="{% url "accounts:follow" following.pk %}" method="POST">
                    {% csrf_token %}
                    {% if following in followings %}
                      <button>팔로우 취소</button>
                    {% else %}
                      <button>팔로우</button>
                    {% endif %}
                  </form>
                </div>
                {% if not forloop.last %}
                  <br>
                {% endif %}
                {% endfor %}
              {% else %}
                <div>팔로우 중인 친구가 없습니다. 친구 찾기 기능을 사용해보세요!</div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="followers" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">팔로워({{ followers.count }})</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              {% if followers.count > 0 %}
                {% for follower in followers %}
                <div class="friend-box">
                  <div class="friend-info-box">
                    {% if follower.profile_img %}
                      <img src="{{ follower.profile_img.url }}" alt="프로필 이미지">
                    {% else %}
                      <img src="{% static "img/user.png" %}" alt="기본 프로필 이미지">
                    {% endif %}
                    <span>
                      {{ follower.nickname }}({{ follower.username }})
                    </span>
                  </div>
                  <form action="{% url "accounts:follow" follower.pk %}" method="POST">
                    {% csrf_token %}
                    {% if follower in followings %}
                      <button>팔로우 취소</button>
                    {% else %}
                      <button>팔로우</button>
                    {% endif %}
                  </form>
                </div>
                {% if not forloop.last %}
                  <br>
                {% endif %}
                {% endfor %}
              {% else %}
                <div>팔로워가 없습니다. 친구 찾기 기능을 사용해보세요!</div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>

      <div class="account-update-buttons">
        <a href="{% url "accounts:update" %}"><button>회원정보 수정</button></a>
        <a href="{% url "accounts:password_change" %}"><button>비밀번호 변경</button></a>
      </div>
    </div>

    <div class="mypage-box">
      <div class="mypage-box-header">
        <button type="button"><div class="mypage-box-buttons" id="sharedPostButton">공유 일기</div></button>
        <button><div class="mypage-box-buttons" id="commentButton">댓글</div></button>
        <button><div class="mypage-box-buttons" id="findFriendButton">친구 찾기</div></button>
      </div>

      <div class="mypage-box-body">
        <div class="content-1">
          <div class="box-1">
            <h1>나에게 공유된 일기</h1>
            <div class="shared-posts-box">
              {% if shared_posts_to_me %}
                {% for post in shared_posts_to_me %}
                  <a href="{% url "posts:detail" post.user.pk post.date %}">
                    <div class="card">
                      {% if post.post_img %}
                        <img src="{{ post.post_img.url }}" class="card-img-top" alt="일기 이미지">
                      {% else %}
                        <img src="{% static "img/cloud.png" %}" class="card-img-top" alt="일기 이미지">
                      {% endif %}
                      <div class="card-body">
                        <h2 class="card-title text-truncate">{{ post.title }}</h2>
                        <p class="card-text text-truncate">{{ post.content }}</p>
                      </div>
                    </div>
                    <div class="post-list">
                      <ul class="list-group">
                        <li class="list-group-item text-truncate">
                          {{ post.date}} | {{ post.title }}
                        </li>
                      </ul>
                    </div>
                  </a>
                {% endfor %}
              {% else %}
                <p>나에게 공유된 일기가 없습니다.</p>
              {% endif %}
            </div>
          </div>
          <div class="box-2">
            <h1>내가 공유한 일기</h1>
            <div class="shared-posts-box">
              {% if shared_posts_by_me %}
                {% for post in shared_posts_by_me %}
                  <a href="{% url "posts:detail" post.user.pk post.date %}">
                    <div class="card">
                      {% if post.post_img %}
                        <img src="{{ post.post_img.url }}" class="card-img-top" alt="일기 이미지">
                      {% else %}
                        <img src="{% static "img/cloud.png" %}" class="card-img-top" alt="일기 이미지">
                      {% endif %}
                      <div class="card-body">
                        <h2 class="card-title text-truncate">{{ post.title }}</h2>
                        <p class="card-text text-truncate">{{ post.content }}</p>
                      </div>
                    </div>
                    <div class="post-list">
                      <ul class="list-group">
                        <li class="list-group-item text-truncate">
                          {{ post.date}} | {{ post.title }}
                        </li>
                      </ul>
                    </div>
                  </a>
                {% endfor %}
              {% else %}
                <p>내가 공유한 일기가 없습니다.</p>
              {% endif %}
            </div>
          </div>
        </div>

        <div class="content-2">
          <div class="box-1">
            <h1>댓글이 달린 내 일기</h1>
            <div class="shared-posts-box">
              {% if posts_with_comments_by_others %}
                {% for post in posts_with_comments_by_others %}
                  <a href="{% url "posts:detail" post.user.pk post.date %}">
                    <div class="card">
                      {% if post.post_img %}
                        <img src="{{ post.post_img.url }}" class="card-img-top" alt="일기 이미지">
                      {% else %}
                        <img src="{% static "img/cloud.png" %}" class="card-img-top" alt="일기 이미지">
                      {% endif %}
                      <div class="card-body">
                        <h2 class="card-title text-truncate">{{ post.title }}</h2>
                        <p class="card-text text-truncate">{{ post.content }}</p>
                      </div>
                    </div>
                    <div class="post-list">
                      <ul class="list-group">
                        <li class="list-group-item text-truncate">
                          {{ post.date}} | {{ post.title }}
                        </li>
                      </ul>
                    </div>
                  </a>
                {% endfor %}
              {% else %}
                <p>댓글이 달린 일기가 없습니다.</p>
              {% endif %}
            </div>
          </div>
          <div class="box-2">
            <h1>내가 댓글을 단 일기</h1>
            <div class="shared-posts-box">
              {% if posts_with_my_comments %}
                {% for post in posts_with_my_comments %}
                  <a href="{% url "posts:detail" post.user.pk post.date %}">
                    <div class="card">
                      {% if post.post_img %}
                        <img src="{{ post.post_img.url }}" class="card-img-top" alt="일기 이미지">
                      {% else %}
                        <img src="{% static "img/cloud.png" %}" class="card-img-top" alt="일기 이미지">
                      {% endif %}
                      <div class="card-body">
                        <h2 class="card-title text-truncate">{{ post.title }}</h2>
                        <p class="card-text text-truncate">{{ post.content }}</p>
                      </div>
                    </div>
                    <div class="post-list">
                      <ul class="list-group">
                        <li class="list-group-item text-truncate">
                          {{ post.date}} | {{ post.title }}
                        </li>
                      </ul>
                    </div>
                  </a>
                {% endfor %}
              {% else %}
                <p>내가 댓글을 단 일기가 없습니다.</p>
              {% endif %}
            </div>
          </div>
        </div>

        <div class="content-3">
          <h1>친구 찾기</h1>
          <div class="friend-search">
            <input type="text" id="friendSearchInput" class="form-control" placeholder="친구의 아이디 또는 닉네임을 검색해보세요!">
            <button onclick="searchFriends()">검색</button>
          </div>
          <div id="friendSearchResults" class="friend-search-results"></div>
      </div>      

    </div>
  </div>
{% endblock content %}

{% block js %}
<script src="{% static "js/mypage.js" %}"></script>
{% endblock js %}

accounts/templates/accounts/password_change.html
{% extends "base.html" %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static "css/password_change.css" %}">
{% endblock style %}

{% block content %}
  <div class="main-box">
    <h2>비밀번호 변경</h2>
    <div class="password-change-form">
      <form action="{% url "accounts:password_change" %}" method="POST">
        {% csrf_token %}
        {% for inputs in form %}
          {% if inputs.name == "new_password1" %}
          <label>{{inputs.label}}
            <div id="passwordValidationMessage" class="validation-message"></div>
            <p id="inputs">{{inputs}}</p>
          </label>
          {% elif inputs.name == "new_password2" %}
            <label>{{inputs.label}}
              <span id="passwordMismatchMessage" class="mismatch-message"></span>
              <p id="inputs">{{inputs}}</p>
            </label>
          {% else %}
            <label>{{inputs.label}}
              <p id="inputs">{{inputs}}</p>
            </label>
          {% endif %}
        {% endfor %}
        <button id="password-update-button" type="submit" disabled>비밀번호 변경</button>
      </form>
    </div>
    <a class="back-button" href="{% url "accounts:mypage" %}">
      <i class="fa-solid fa-arrow-left"></i>돌아가기
    </a>
  </div>
{% endblock content %}

{% block js %}
  <script src="{% static "js/password_change.js" %}"></script>
  <script>
    {% if messages %}
      {% for message in messages %}
        alert("{{ message }}")
      {% endfor %}
    {% endif %}
  </script>
{% endblock js %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static "css/signup.css" %}">
{% endblock style %}

{% block content %}
  <div class="main-box">
    <h2>회원가입</h2>
    <p>* 표시 항목은 필수 입력 항목입니다.</p>
    <div class="signup-form">
      <form action="{% url "accounts:signup" %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for inputs in form %}
          {% if inputs.name == "username" %}
            <label>{{inputs.label}}
              <span id="username-length-count"></span>
              <span id="username-message" class="duplicate-message"></span>
              <p id="inputs">{{inputs}}</p>
            </label>
          {% elif inputs.name == "nickname" %}
            <label>{{inputs.label}}
              <span id="nickname-length-count"></span>
              <span id="nickname-message" class="duplicate-message"></span>
              <p id="inputs">{{inputs}}</p>
            </label>
          {% elif inputs.name == "password1" %}
            <label>{{inputs.label}}
              <div id="passwordValidationMessage" class="validation-message"></div>
              <p id="inputs">{{inputs}}</p>
            </label>
          {% elif inputs.name == "password2" %}
            <label>{{inputs.label}}
              <span id="passwordMismatchMessage" class="mismatch-message"></span>
              <p id="inputs">{{inputs}}</p>
            </label>
          {% elif inputs.name == "profile_img" %}
            <label for="id_profile_img">{{inputs.label}}
              <input type="file" name="profile_img" id="id_profile_img" accept="image/*" onchange="previewImage(this)">
            </label>
          {% endif %}
          <br>
        {% endfor %}
        <div class="image-box">
          <img class="preview" src="#" alt="프로필 이미지 미리보기">
        </div>
        <button id="signup-button" type="submit" disabled>회원가입</button>
      </form>
    </div>
    <a class="back-button" href="{% url "accounts:login" %}">
      <i class="fa-solid fa-arrow-left"></i>돌아가기
    </a>
  </div>
{% endblock content %}

{% block js %}
  <script src="{% static "js/signup.js" %}"></script>
{% endblock js %}

accounts/templates/accounts/update.html
{% extends "base.html" %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static "css/update.css" %}">
{% endblock style %}

{% block content %}
  <div class="main-box">
    <h2>회원정보 수정</h2>
    <p>* 표시 항목은 필수 입력 항목입니다.</p>
    <div class="update-form">
      <form action="{% url "accounts:update" %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for inputs in form %}
          {% if inputs.label != "비밀번호" %}
            {% if inputs.name == "nickname" %}
              <label>{{inputs.label}}
                <span id="length_count" class="length_count"></span>
                <span id="nickname-message" class="duplicate-message"></span>
                <p id="inputs">{{inputs}}</p>
              </label>
            {% else %}
            <label>{{inputs.label}}
              <p id="inputs">{{inputs}}</p>
            </label>
            {% endif %}
          {% endif %}
        {% endfor %}

        <div class="image-box">
          {% if request.user.profile_img %}
            <img class="preview-1" src={{ request.user.profile_img.url }} alt="프로필 이미지 미리보기">
          {% else %}
            <img class="preview-2" src="#" alt="프로필 이미지 미리보기">
          {% endif %}
        </div>
        <button id="update-button" type="submit">회원정보 수정</button>
      </form>
    </div>
    <form class="delete-form" action="{% url "accounts:delete" %}" method="POST">
      {% csrf_token %}
      <button class="delete-button" type="submit">회원탈퇴</button>
    </form>
    <a class="back-button" href="{% url "accounts:mypage" %}">
      <i class="fa-solid fa-arrow-left"></i>돌아가기
    </a>
  </div>
{% endblock content %}


{% block js %}
  <script>const currentUserNickname = "{{ request.user.nickname }}";</script>
  <script src="{% static "js/update.js" %}"></script>
{% endblock js %}