accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("update/", views.update, name="update"),
    path("delete/", views.delete, name="delete"),
    path("password_change/", views.password_change, name="password_change"),
    path("follow/<int:user_pk>/", views.follow, name="follow"),
    path("mypage/", views.mypage, name="mypage"),
    path(
        "search_friends/<str:search_query>/",
        views.search_friends,
        name="search_friends",
    ),
    path("check_duplicate/", views.check_duplicate, name="check_duplicate"),
    path(
        "mark_as_read/<int:notification_pk>/", views.mark_as_read, name="mark_as_read"
    ),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path("main/", views.main, name="main"),
    path("create/<str:post_date>/", views.create, name="create"),
    path("check_post/<str:post_date>/", views.check_post, name="check_post"),
    path("detail/<int:user_pk>/<str:post_date>/", views.detail, name="detail"),
    path("update/<int:post_pk>/", views.update, name="update"),
    path("delete/<int:post_pk>/", views.delete, name="delete"),
    path("comment_create/<int:post_pk>/", views.comment_create, name="comment_create"),
    path(
        "comment_delete/<int:post_pk>/<int:comment_pk>/",
        views.comment_delete,
        name="comment_delete",
    ),
    path(
        "comment_update/<int:post_pk>/<int:comment_pk>/",
        views.comment_update,
        name="comment_update",
    ),
]

skyful/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("accounts/", include("accounts.urls")),
    path("posts/", include("posts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Dongle&family=Poppins&display=swap"
      rel="stylesheet"
    />
    <script
      src="https://kit.fontawesome.com/e4df03fd8f.js"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{% static "css/base.css" %}"> <link
    rel="shortcut icon" href="{% static "img/cloud.png" %}">
    <title>SKYFUL</title>
    {% block style %} {% endblock style %}
  </head>

  <body>
    {% include "nav.html" %}

    <div class="container">{% block content %} {% endblock content %}</div>

    {% block js %} {% endblock js %}

    <script src="{% static 'js/nav.js' %}"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/nav.html
{% load static %}
{% load custom_filters %}

<head>
  <link rel="stylesheet" href="{% static "css/nav.css" %}">
</head>

<nav>
  <div class="navbar">
    <div class="navbar-left">
      <a href="{% url "posts:main" %}">
        <img src="{% static "img/cloud.png" %}" alt="구름 로고">
        <h1>당신의 하늘</h1>
      </a>
    </div>
    {% if user.is_authenticated %}
      <div class="navbar-right">
        <div class="dropstart">
          <button class="dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            {% if request.user|unread_notifications %}
              <i class="fa-solid fa-bell">
                <span></span>
              </i>
                
            {% else %}
              <i class="fa-regular fa-bell"></i>
            {% endif %}
          </button>
          <ul class="dropdown-menu">
            {% if request.user|unread_notifications %}
              {% for notification in request.user|unread_notifications %}
                <li>
                  <form action="{% url "accounts:mark_as_read" notification.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="mark-as-read-btn" data-notification-id="{{ notification.pk }}"><i class="fa-solid fa-xmark"></i></button>
                    <div>{{ notification.message }}</div>
                  </form>
                </li>
              {% endfor %}
            {% else %}
              <li>
                <div>새로운 알림이 없습니다.</div>
              </li>
            {% endif %}
          </ul>
        </div>
        <div class="navbar-right-menu-1">
          <a class="buttons" href="{% url "accounts:mypage" %}">마이페이지</a>
          <form action="{% url "accounts:logout" %}" method="POST">
            {% csrf_token %}
            <button class="buttons" type="submit">로그아웃</button>
          </form>
        </div>
        <div class="navbar-right-menu-2">
          <a data-bs-toggle="collapse" href="#menu" role="button" aria-expanded="false" aria-controls="collapseExample">
            <i class="fa-solid fa-bars"></i>
          </a>
        </div>
      </div>
    {% endif %}
  </div>
  <div class="collapse" id="menu">
    <div class="card card-body">
      <a href="{% url "accounts:mypage" %}">마이페이지</a>
      <form action="{% url "accounts:logout" %}" method="POST">
        {% csrf_token %}
        <button type="submit">로그아웃</button>
      </form>
    </div>
  </div>
</nav>