posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path("main/", views.main, name="main"),
    path("create/<str:post_date>/", views.create, name="create"),
    path("check_post/<str:post_date>/", views.check_post, name="check_post"),
    path("detail/<int:user_pk>/<str:post_date>/", views.detail, name="detail"),
    path("update/<int:post_pk>/", views.update, name="update"),
    path("delete/<int:post_pk>/", views.delete, name="delete"),
    path("comment_create/<int:post_pk>/", views.comment_create, name="comment_create"),
    path(
        "comment_delete/<int:post_pk>/<int:comment_pk>/",
        views.comment_delete,
        name="comment_delete",
    ),
    path(
        "comment_update/<int:post_pk>/<int:comment_pk>/",
        views.comment_update,
        name="comment_update",
    ),
]

skyful/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("accounts/", include("accounts.urls")),
    path("posts/", include("posts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=50)
    content = models.TextField()
    weather = models.IntegerField()
    public = models.BooleanField(default=False)
    shared_with = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="shared_posts", blank=True
    )
    post_img = ProcessedImageField(
        upload_to="posts",
        processors=[ResizeToFill(200, 200)],
        options={"quality": 90},
        null=True,
        blank=True,
    )


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    date = forms.CharField(
        label="날짜",
        label_suffix="",
        widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}),
    )
    title = forms.CharField(
        label="제목",
        label_suffix="",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "제목",
            }
        ),
    )
    content = forms.CharField(
        label="내용",
        label_suffix="",
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "내용",
            }
        ),
    )
    weather = forms.ChoiceField(
        label="날씨",
        label_suffix="",
        widget=forms.RadioSelect(
            attrs={"class": "form-check-input"},
        ),
        choices=[(1, "맑음"), (2, "흐림"), (3, "비"), (4, "눈")],
    )
    post_img = forms.ImageField(
        label="이미지(선택)", widget=forms.ClearableFileInput(), required=False
    )

    class Meta:
        model = Post
        fields = (
            "date",
            "weather",
            "title",
            "content",
            "post_img",
        )


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label="댓글",
        label_suffix="",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "댓글",
            }
        ),
    )

    class Meta:
        model = Comment
        fields = ("content",)

posts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .forms import PostForm, CommentForm
from .models import Post, Comment
from accounts.models import Notification
from datetime import datetime
from calendar import monthrange
import os


def main(request):
    if request.user.is_authenticated:
        current_year = datetime.now().year
        current_month = datetime.now().month
        future_years = range(current_year, current_year + 6)
        months_range = range(1, 13)
        days_of_week = ["일", "월", "화", "수", "목", "금", "토"]

        context = {
            "current_year": current_year,
            "current_month": current_month,
            "future_years": future_years,
            "months_range": months_range,
            "days_of_week": days_of_week,
        }
        return render(request, "posts/main.html", context)
    else:
        return redirect("accounts:login")


@login_required
def create(request, post_date):
    User = get_user_model()
    person = User.objects.get(pk=request.user.pk)
    post_date = datetime.strptime(post_date, "%Y-%m-%d").date()

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = person
            post.public = request.POST.get("public") == "on"
            post.save()

            shared_users = request.POST.getlist("shared_with")
            post.shared_with.set(shared_users)
            return redirect("posts:main")
    else:
        form = PostForm(initial={"date": post_date})

    followings = person.followings.all()
    followers = person.followers.all()
    friends = followings & followers

    context = {
        "form": form,
        "date": post_date,
        "friends": friends,
    }
    return render(request, "posts/create.html", context)


@login_required
def check_post(request, post_date):
    try:
        post = Post.objects.get(user=request.user, date=post_date)
        return JsonResponse({"has_post": True})
    except Post.DoesNotExist:
        return JsonResponse({"has_post": False})


@login_required
def detail(request, user_pk, post_date):
    post = Post.objects.get(user=user_pk, date=post_date)
    comments = post.comment_set.all()
    context = {
        "post": post,
        "comments": comments,
        "form": CommentForm(),
    }
    return render(request, "posts/detail.html", context)


@login_required
def update(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    User = get_user_model()
    person = User.objects.get(pk=request.user.pk)

    if request.user != post.user:
        return redirect("posts:main")

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.public = request.POST.get("public") == "on"
            post.save()

            shared_users = request.POST.getlist("shared_with")
            post.shared_with.set(shared_users)

            return redirect("posts:detail", post.user.pk, post.date)
    else:
        form = PostForm(instance=post)

    weather = post.weather
    followings = person.followings.all()
    followers = person.followers.all()
    friends = followings & followers

    context = {
        "post": post,
        "form": form,
        "weather": weather,
        "friends": friends,
    }
    return render(request, "posts/update.html", context)


@login_required
def delete(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.user == post.user:
        if post.post_img:
            if os.path.isfile(post.post_img.path):
                os.remove(post.post_img.path)
        post.delete()
    return redirect("posts:main")


@login_required
def comment_create(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()

            if post.user != request.user:
                Notification.objects.create(
                    user=post.user,
                    message=f"{request.user.nickname}님이 당신의 {post.date} 일기에 댓글을 달았습니다.",
                )
            return redirect("posts:detail", post.user.pk, post.date)


@login_required
def comment_delete(request, post_pk, comment_pk):
    post = Post.objects.get(pk=post_pk)
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect("posts:detail", post.user.pk, post.date)


@login_required
def comment_update(request, post_pk, comment_pk):
    post = Post.objects.get(pk=post_pk)
    comment = Comment.objects.get(pk=comment_pk)

    if request.user != comment.user:
        return redirect("posts:detail", post.user.pk, post.date)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect("posts:detail", post.user.pk, post.date)
    return redirect("posts:detail", post.user.pk, post.date)

posts/templates/posts/create.html
{% extends "base.html" %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static "css/create.css" %}">
{% endblock style %}

{% block content %}
  <div class="main-box">
    <h2>일기 작성</h2>
    <div class="create-form">
      <form action="{% url "posts:create" date %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for inputs in form %}
          {% if inputs.name == "title" %}
            <label>{{inputs.label}}
              <span id="length_count" class="length_count"></span>
              <p id="inputs">{{inputs}}</p>
            </label>
          {% elif inputs.name == "weather" %}
            <label class="weather">{{inputs.label}}</label>
            <div class="weather-box">
              {% for value, label in form.fields.weather.choices %}
                <label class="weather-radio" for="weather_{{ value }}">
                  <input class="form-check-input" type="radio" name="weather" value="{{ value }}" id="weather_{{ value }}">
                  <img src="{% get_static_prefix %}img/weather_{{ value }}.png" alt="{{ label }}" class="weather-image">
                </label>
              {% endfor %}
            </div>
          {% elif inputs.name == "post_img" %}
            <label for="id_post_img">{{inputs.label}}
              <input type="file" name="post_img" id="id_post_img" accept="image/*" onchange="previewImage(this)">
            </label>
          {% else %}
            <label>{{inputs.label}}
              <p id="inputs">{{inputs}}</p>
            </label>
          {% endif %}
          <br>
        {% endfor %}
        <div class="image-box">
          <img class="preview" src="#" alt="프로필 이미지 미리보기">
        </div>

        <div class="form-check form-switch public-check">
          <label class="form-check-label" for="public">공유(서로 친구일 때만 가능)</label>
          <input class="form-check-input" type="checkbox" role="switch" id="public" name="public">
        </div>

        <div class="friend-check">
          {% for friend in friends %}
            <div class="form-check">
              <input class="form-check-input" type="checkbox" name="shared_with" value="{{ friend.id }}" id="friend{{ friend.id }}">
              <label class="form-check-label" for="friend{{ friend.id }}">
                {% if friend.profile_img %}
                  <img src="{{ friend.profile_img.url }}" alt="프로필 이미지">
                {% else %}
                  <img src="{% static "img/user.png" %}" alt="기본 프로필 이미지">
                {% endif %}
                <div>
                  {{ friend.nickname }} ({{ friend.username }})
                </div>
              </label>
            </div>
          {% endfor %}
        </div>

        <button type="submit">작성하기</button>
      </form>
    </div>
    <a class="back-button" href="{% url "posts:main" %}">
      <i class="fa-solid fa-arrow-left"></i>돌아가기
    </a>
  </div>
{% endblock content %}

{% block js %}
  <script src="{% static "js/create.js" %}"></script>
{% endblock js %}

posts/templates/posts/detail.html
{% extends "base.html" %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static "css/detail.css" %}">
{% endblock style %}

{% block content %}
  <div class="main-box">
    <div class="post-box">
      <div class="post-date-weather">
        {{ post.date|date:"Y.m.d" }}
        <img src="{% get_static_prefix %}img/weather_{{ post.weather }}.png" class="weather-image">
      </div>
      <h1>{{ post.title }}</h1>
      <div class="post-info-box">
        <div class="post-public-nickname">
          <span class="post-user-nickname">{{ post.user.nickname }}</span>
          {% if post.shared_with.count > 0 %}
            <span class="public">공유중</span>
          {% else %}
            <span class="private">비공개</span>
          {% endif %}
        </div>
      </div>
      <hr>
      {% if request.user == post.user %}
        <div class="post-buttons">
          <a class="update-button" href="{% url 'posts:update' post.pk %}"><i class="fa-solid fa-pen-to-square"></i> 수정</a>
          <form class="delete-form" action="{% url "posts:delete" post.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit"><i class="fa-solid fa-trash-can"></i> 삭제</button>
          </form>
        </div>            
      {% endif %}

      {% if post.post_img %}
        <div class="post-image">
          <img src="{{ post.post_img.url }}" alt="일기 사진">
        </div>
      {% endif %}

      <div class="post-content">
        {{ post.content }}
      </div>

      <div class="comment-writing-box">
        <form method="POST" action="{% url "posts:comment_create" post.pk %}">
          {% csrf_token %}
          <div class="comment-content-box">
            {{ form.content }}
            <button type="submit">댓글달기</button>
          </div>
        </form>
      </div>

      {% if comments.count > 0 %}
        <div class="accordion accordion-flush">
          <div class="accordion-item">
            <div class="accordion-header">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                댓글({{ comments.count }})
              </button>
            </div>
            
            {% for comment in comments %}
              <div id="collapseOne" class="accordion-collapse collapse">
                <div class="accordion-body">
                  <div class="comment-detail-box">
                    <div class="comment-writer-info">
                      {% if comment.user.profile_img %}
                        <img src="{{ comment.user.profile_img.url }}" alt="프로필 이미지">
                      {% else %}
                        <img src="{% static "img/user.png" %}" alt="기본 프로필 이미지">
                      {% endif %}
                      <div class="comment-nickname-date">
                        <div>{{ comment.user.nickname }}</div>
                        <div class="comment-date">{{ comment.created_at|date:"Y-m-d, H:i" }}</div>
                      </div>
                    </div>
                    <div class="comment-buttons">
                      {% if request.user == comment.user %}
                        <a class="comment-update-button" href="#" data-comment-id="{{ comment.pk }}">
                          <i class="fa-solid fa-pen-to-square"></i> 수정
                        </a>
                        <form class="delete-form" action="{% url "posts:comment_delete" post.pk comment.pk %}" method="POST">
                          {% csrf_token %}
                          <button><i class="fa-solid fa-trash-can"></i> 삭제</button>
                        </form>
                      {% endif %}
                    </div>
                  </div>
                  <div class="comment-content">
                    {{ comment.content }}
                  </div>
                  <div class="update-comment-form-box">
                    <form action="{% url "posts:comment_update" post.pk comment.pk %}" method="POST" class="update-comment-form" id="update-comment-form-{{ comment.pk }}" data-comment-id="{{ comment.pk }}">
                      {% csrf_token %}
                      <textarea class="update-comment-content form-control form-field" name="content" required>{{ comment.content }}</textarea>
                      <button type="submit">수정</button>
                    </form>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      {% endif %}
    </div>
    <a class="back-button" href="{% url "posts:main" %}">
      <i class="fa-solid fa-arrow-left"></i>돌아가기
    </a>
  </div>
{% endblock content %}

{% block js %}
  <script src="{% static "js/detail.js" %}"></script>
{% endblock js %}

posts/templates/posts/main.html
{% extends "base.html" %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static "css/main.css" %}">
{% endblock style%}

{% block content %}
  <div class="main-box">
    <header>
      <h1>일기 달력</h1>
      <select id="year" onchange="updateCalendar()">
        {% for year in future_years %}
          <option {% if year == current_year %}selected{% endif %}>{{ year }}년</option>
        {% endfor %}
      </select>
      <select id="month" onchange="updateCalendar()">
        {% for month in months_range %}
          <option {% if month == current_month %}selected{% endif %}>{{ month }}월</option>
        {% endfor %}
      </select>
    </header>

    <div class="calendar">
      <div class="month" id="currentMonth"></div>
      <div class="days" id="calendarDays">
        {% for day in days_of_week %}
          <div class="day day-of-week">{{ day }}</div>
        {% endfor %}

        {% for day in empty_days %}
          <div class="day empty"></div>
        {% endfor %}

        {% for day in days_in_month %}
          <div class="day">{{ day }}</div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}

{% block js %}
  <script>const userPk = {{ request.user.pk }};</script>
  <script src="{% static "js/main.js" %}"></script>
{% endblock js %}

posts/templates/posts/update.html
{% extends "base.html" %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static "css/post_update.css" %}">
{% endblock style %}

{% block content %}
  <div class="main-box">
    <h2>일기 수정</h2>
    <div class="update-form">
      <form action="{% url "posts:update" post.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for inputs in form %}
          {% if inputs.name == "title" %}
            <label>{{inputs.label}}
              <span id="length_count" class="length_count"></span>
              <p id="inputs">{{inputs}}</p>
            </label>
          {% elif inputs.name == "weather" %}
            <label class="weather">{{inputs.label}}</label>
            <div class="weather-box">
              {% for value, label in form.fields.weather.choices %}
                <label class="weather-radio" for="weather_{{ value }}">
                  <input class="form-check-input" type="radio" name="weather" value="{{ value }}" id="weather_{{ value }}" 
                  {% if value == weather %}checked{% endif %}>
                  <img src="{% get_static_prefix %}img/weather_{{ value }}.png" alt="{{ label }}" class="weather-image">
                </label>
              {% endfor %}
            </div>
          {% elif inputs.name == "post_img" %}
            <label for="id_post_img">{{inputs.label}}
              <input type="file" name="post_img" id="id_post_img" accept="image/*">
            </label>
          {% else %}
            <label>{{inputs.label}}
              <p id="inputs">{{inputs}}</p>
            </label>
          {% endif %}
          <br>
        {% endfor %}
        
        <div class="image-box">
          {% if post.post_img %}
            <img class="preview-1" src={{ post.post_img.url }} alt="프로필 이미지 미리보기">
          {% else %}
            <img class="preview-2" src="#" alt="프로필 이미지 미리보기">
          {% endif %}
        </div>

        <div class="form-check form-switch public-check">
          <label class="form-check-label" for="public">공유(서로 친구일 때만 가능)</label>
          {% if post.shared_with.count > 0 %}
            <input class="form-check-input" type="checkbox" role="switch" id="public" name="public" checked>
          {% else %}
            <input class="form-check-input" type="checkbox" role="switch" id="public" name="public">
          {% endif %}
        </div>

        <div class="friend-check">
          {% for friend in friends %}
            <div class="form-check">
              {% if friend in post.shared_with.all %}
                <input class="form-check-input" type="checkbox" name="shared_with" value="{{ friend.id }}" id="friend{{ friend.id }}" checked>
              {% else %}
                <input class="form-check-input" type="checkbox" name="shared_with" value="{{ friend.id }}" id="friend{{ friend.id }}">
              {% endif %}
              
              <label class="form-check-label" for="friend{{ friend.id }}">
                {% if friend.profile_img %}
                  <img src="{{ friend.profile_img.url }}" alt="프로필 이미지">
                {% else %}
                  <img src="{% static "img/user.png" %}" alt="기본 프로필 이미지">
                {% endif %}
                <div>
                  {{ friend.nickname }} ({{ friend.username }})
                </div>
              </label>
            </div>
          {% endfor %}
        </div>
        <button type="submit">수정하기</button>
      </form>
    </div>
    <a class="back-button" href="{% url "posts:main" %}">
      <i class="fa-solid fa-arrow-left"></i>돌아가기
    </a>
  </div>
{% endblock content %}

{% block js %}
  <script src="{% static "js/post_update.js" %}"></script>
{% endblock js %}